packages:
  - "apps/*"
  - "packages/*"

overrides:
  sharp: ">=0.35.0"
  postcss: ">=8.5.18"
  deepmerge-ts: ">=8.0.0"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  argon2: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "prisma"
  - "sharp"
