import Link from "next/link";
import { ArrowLeft, LockKeyhole } from "lucide-react";
import { BrandMark } from "@/components/brand-mark";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export const metadata = { title: "Secure checkout" };

export default function CheckoutPage() {
  return <main className="min-h-screen bg-[#eee9df]"><header className="border-b border-ink/10 bg-paper px-5 py-5"><div className="mx-auto flex max-w-[1100px] items-center justify-between"><BrandMark /><span className="flex items-center gap-2 text-[11px] font-semibold text-ink/50"><LockKeyhole className="size-3.5" /> Secure checkout</span></div></header><section className="mx-auto grid max-w-[1100px] gap-8 px-5 py-10 lg:grid-cols-[1fr_400px]"><div><Link href="/cart" className="flex items-center gap-2 text-xs font-semibold text-ink/55"><ArrowLeft className="size-4" /> Back to basket</Link><h1 className="mt-8 font-display text-5xl font-semibold">Delivery details</h1><form className="mt-8 grid gap-4 rounded-[28px] bg-white/60 p-6 shadow-soft sm:grid-cols-2 sm:p-8"><label className="text-xs font-semibold">First name<input className="field mt-2" autoComplete="given-name" /></label><label className="text-xs font-semibold">Last name<input className="field mt-2" autoComplete="family-name" /></label><label className="text-xs font-semibold sm:col-span-2">Email<input className="field mt-2" type="email" autoComplete="email" /></label><label className="text-xs font-semibold sm:col-span-2">Address<input className="field mt-2" autoComplete="street-address" /></label><label className="text-xs font-semibold">Town or city<input className="field mt-2" autoComplete="address-level2" /></label><label className="text-xs font-semibold">Postcode<input className="field mt-2" autoComplete="postal-code" /></label></form></div><aside className="surface h-fit p-7 lg:mt-16"><p className="eyebrow">Payment</p><h2 className="mt-3 font-display text-3xl font-semibold">Complete securely</h2><p className="mt-3 text-xs leading-5 text-ink/50">Stripe Payment Element mounts here when credentials are configured. Server-side order repricing and webhook confirmation remain authoritative.</p><div className="mt-6 rounded-2xl border border-dashed border-forest/25 bg-forest/[.035] p-6 text-center text-xs text-ink/45">Secure card fields</div><button className={cn(buttonVariants({ variant: "primary", size: "lg" }), "mt-6 w-full")}>Review and pay</button></aside></section></main>;
}
