import { ArrowRight, FileSpreadsheet, Filter, Plus, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { orders, products } from "@/lib/catalogue";
import { formatMoney } from "@/lib/utils";

const copy: Record<string, { title: string; description: string }> = {
  orders: { title: "Orders", description: "Search, review and follow every order from placement to delivery." },
  favourites: { title: "Saved pieces", description: "A considered shortlist, ready whenever you are." },
  profile: { title: "Profile & addresses", description: "Manage contact details, delivery addresses and preferences." },
  catalogue: { title: "Catalogue", description: "Manage products, visibility, attributes, media and availability." },
  invoices: { title: "Invoices", description: "Review invoice history and securely download account documents." },
  team: { title: "Account team", description: "Invite buyers and control who can view or place orders." },
  customers: { title: "Customers", description: "Manage consumer and trade relationships in one trusted record." },
  activity: { title: "Customer activity", description: "Follow recent orders, conversations and reorder signals." },
  fulfilment: { title: "Fulfilment", description: "Manage partial dispatches, tracking and delivery exceptions." },
  integrations: { title: "Integration centre", description: "Monitor stock, orders, invoices, failures and recovery." },
  settings: { title: "Platform settings", description: "Configure commerce rules, access, delivery, VAT and content." },
};

export function WorkspaceSection({ section }: { section: string }) {
  const details = copy[section] ?? { title: section.replaceAll("-", " "), description: "Manage this Gemjar workspace." };
  const showOrders = section === "orders" || section === "fulfilment";
  const showProducts = section === "catalogue" || section === "favourites";
  if (section === "integrations") return <><div className="mb-6"><h2 className="font-display text-3xl font-semibold">{details.title}</h2><p className="mt-2 text-xs text-ink/45">{details.description}</p></div><div className="grid gap-4 lg:grid-cols-2">{[["Mintsoft", "Demo fallback", "Stock captured 11 minutes ago", "warn"], ["Sage 50", "Mock provider", "Live connection intentionally disabled", "neutral"]].map(([name, status, note, tone]) => <article key={name} className="surface p-6"><div className="flex justify-between"><div><p className="font-display text-2xl font-semibold">{name}</p><p className="mt-1 text-xs text-ink/40">{note}</p></div><Badge tone={tone as "warn" | "neutral"}>{status}</Badge></div><div className="mt-7 grid grid-cols-3 gap-3 text-center"><div className="rounded-xl bg-white/50 p-3"><b className="block text-lg">0</b><span className="text-[9px] uppercase tracking-wider text-ink/40">Pending</span></div><div className="rounded-xl bg-white/50 p-3"><b className="block text-lg">0</b><span className="text-[9px] uppercase tracking-wider text-ink/40">Failed</span></div><div className="rounded-xl bg-white/50 p-3"><b className="block text-lg">100%</b><span className="text-[9px] uppercase tracking-wider text-ink/40">Success</span></div></div></article>)}</div></>;
  return <section className="surface overflow-hidden"><div className="flex flex-col justify-between gap-5 border-b border-ink/10 p-6 sm:flex-row sm:items-end"><div><h2 className="font-display text-3xl font-semibold capitalize">{details.title}</h2><p className="mt-2 text-xs text-ink/45">{details.description}</p></div><div className="flex gap-2"><Button variant="secondary" size="sm"><FileSpreadsheet className="size-3.5" /> Export</Button><Button size="sm"><Plus className="size-3.5" /> Add new</Button></div></div><div className="flex gap-3 border-b border-ink/[.07] p-4"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-ink/35" /><input className="field h-9 pl-9" placeholder={`Search ${details.title.toLowerCase()}…`} /></div><Button variant="secondary" size="sm"><Filter className="size-3.5" /> Filter</Button></div>{showOrders ? <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="bg-ink/[.025] text-[10px] uppercase tracking-wider text-ink/38"><tr><th className="px-6 py-3">Order</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Channel</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">Status</th><th /></tr></thead><tbody>{orders.map((order) => <tr key={order.id} className="border-t border-ink/[.06]"><td className="px-6 py-4 font-bold">{order.id}</td><td className="px-4 py-4">{order.customer}</td><td className="px-4 py-4 text-ink/45">{order.channel}</td><td className="px-4 py-4 font-semibold">{formatMoney(order.total)}</td><td className="px-4 py-4"><Badge tone={order.status === "Stock check" ? "warn" : "good"}>{order.status}</Badge></td><td className="px-6 text-right"><ArrowRight className="inline size-4 text-ink/30" /></td></tr>)}</tbody></table></div> : showProducts ? <div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-4">{products.map((product) => <article key={product.id} className="rounded-2xl border border-ink/[.07] bg-white/45 p-4"><p className="text-[10px] uppercase tracking-wider text-ink/35">{product.sku}</p><p className="mt-2 font-display text-xl font-semibold">{product.name}</p><p className="mt-2 text-xs font-bold">{formatMoney(product.price)}</p></article>)}</div> : <div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-3">{[1,2,3,4,5,6].map((item) => <div key={item} className="rounded-2xl border border-ink/[.07] bg-white/40 p-5"><div className="size-10 rounded-xl bg-forest/[.08]" /><div className="mt-4 h-3 w-1/2 rounded bg-ink/10" /><div className="mt-2 h-2 w-3/4 rounded bg-ink/[.06]" /></div>)}</div>}</section>;
}
