import { AlertTriangle, BadgePoundSterling, Boxes, ShoppingBag } from "lucide-react";
import { MetricCard } from "@/components/metric-card";
import { PortalShell } from "@/components/portal-shell";
import { Badge } from "@/components/ui/badge";
import { orders } from "@/lib/catalogue";
import { formatMoney } from "@/lib/utils";

export const metadata = { title: "Operations" };

export default function AdminPage() {
  return <PortalShell kind="admin" title="Good morning, Amara."><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={BadgePoundSterling} label="Gross revenue today" value="£14.8k" note="12.4%" /><MetricCard icon={ShoppingBag} label="Orders today" value="38" note="8.1%" /><MetricCard icon={Boxes} label="Awaiting fulfilment" value="17" note="5 urgent" trend="neutral" /><MetricCard icon={AlertTriangle} label="Needs attention" value="6" note="2 new" trend="down" /></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.6fr]"><section className="surface overflow-hidden"><div className="flex items-center justify-between border-b border-ink/10 p-6"><div><p className="font-display text-2xl font-semibold">Order activity</p><p className="mt-1 text-[11px] text-ink/45">Across online, trade and agents</p></div><button className="text-xs font-bold text-forest">View all</button></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="bg-ink/[.025] text-[10px] uppercase tracking-wider text-ink/38"><tr><th className="px-6 py-3">Order</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Channel</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">Status</th><th className="px-6 py-3 text-right">Age</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id} className="border-t border-ink/[.06]"><td className="px-6 py-4 font-bold">{order.id}</td><td className="px-4 py-4">{order.customer}</td><td className="px-4 py-4 text-ink/50">{order.channel}</td><td className="px-4 py-4 font-semibold">{formatMoney(order.total)}</td><td className="px-4 py-4"><Badge tone={order.status === "Stock check" ? "warn" : order.status === "Part dispatched" ? "neutral" : "good"}>{order.status}</Badge></td><td className="px-6 py-4 text-right text-ink/40">{order.age}</td></tr>)}</tbody></table></div></section>
      <section className="surface p-6"><p className="font-display text-2xl font-semibold">Operational pulse</p><p className="mt-1 text-[11px] text-ink/45">Exceptions requiring action</p><div className="mt-6 space-y-3">{[["Mintsoft stock stale", "3 SKUs · 11 min", "warn"], ["B2B approvals", "2 applications", "neutral"], ["Partial shipments", "4 in progress", "neutral"], ["Failed jobs", "All clear", "good"]].map(([title, note, tone]) => <div key={title} className="flex items-center justify-between rounded-2xl border border-ink/[.07] bg-white/40 p-4"><div><p className="text-xs font-bold">{title}</p><p className="mt-1 text-[10px] text-ink/40">{note}</p></div><span className={`size-2 rounded-full ${tone === "warn" ? "bg-amber-500" : tone === "good" ? "bg-emerald-500" : "bg-ink/20"}`} /></div>)}</div></section></div></PortalShell>;
}
